### ISSUE TITLE
有联系的QQ群不？觉得项目挺有意思，方便一起玩耍不

### ISSUE THREAD

**Issue by cppfuns** [kilmas/QHWallet#1]
哈哈哈

**Comment by kilmas** [comment]
哈，没有，刚好建一个
![Uploading qrcode_1603365416147.jpg…]()

**Comment by kilmas** [comment]
#

- [ ] 

1. `[](url)`

**Comment by kilmas** [comment]
![qrcode_1603365416147](https://user-images.githubusercontent.com/15965206/96865474-990aaf00-149c-11eb-9fe3-97b3dbfaa082.jpg)
没有，哈，刚好建一个

**Comment by MRdoulestar** [comment]
请问还有群吗
